# Generated by Django 4.1 on 2022-08-27 13:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('27e8c8c9-f70d-479a-8bed-f27effe5a39b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
